[build]
  command = "npm run build" # ou o comando que você usa para construir seu site
  publish = "dist" # ou a pasta onde seu site é construído (geralmente "dist" para projetos Vite)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
